services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    container_name: emr-calendar-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: emr-calendar-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules